import React, { useState, useEffect } from 'react';
import { NovelSeoMeta, IntellectualItem } from '../types';
import {
  Globe,
  Search,
  Sparkles,
  Smartphone,
  Monitor,
  CheckCircle2,
  Copy,
  Check,
  AlertCircle,
  ExternalLink,
  Code,
  Tag
} from 'lucide-react';

export interface ArticleSeoStudioProps {
  seo: NovelSeoMeta;
  onChange: (updatedSeo: NovelSeoMeta) => void;
  articleTitle: string;
  articleSubtitle?: string;
  articleContent?: string;
  articleAuthor?: string;
  articleCategory?: string;
  articlePublishedAt?: string;
  articleCoverImage?: string;
  articleSlug?: string;
}

export const ArticleSeoStudio: React.FC<ArticleSeoStudioProps> = ({
  seo,
  onChange,
  articleTitle,
  articleSubtitle,
  articleContent,
  articleAuthor = 'أيمن كناني',
  articleCategory = 'فلسفة وفكر معاصر',
  articlePublishedAt,
  articleCoverImage,
  articleSlug,
}) => {
  const [previewDevice, setPreviewDevice] = useState<'mobile' | 'desktop'>('mobile');
  const [copiedSchema, setCopiedSchema] = useState<boolean>(false);
  const [toastMsg, setToastMsg] = useState<string | null>(null);

  const showToast = (msg: string) => {
    setToastMsg(msg);
    setTimeout(() => setToastMsg(null), 3000);
  };

  // Safe defaults
  const metaTitle = seo.metaTitle ?? '';
  const metaDescription = seo.metaDescription ?? '';
  const focusKeywords = seo.focusKeywords ?? '';
  const canonicalUrl = seo.canonicalUrl ?? '';
  const ogImage = seo.ogImage ?? articleCoverImage ?? '';
  const noIndex = Boolean(seo.noIndex);

  const handleUpdate = (field: keyof NovelSeoMeta, value: any) => {
    onChange({
      ...seo,
      [field]: value,
    });
  };

  // Smart Auto-Generator for Article SEO
  const handleAutoGenerate = () => {
    // 1. Meta Title: Target ~50-60 chars
    const brandSuffix = ' | منصة الكاتب أيمن كناني';
    let generatedTitle = articleTitle.trim();
    if (generatedTitle.length + brandSuffix.length <= 60) {
      generatedTitle = `${generatedTitle}${brandSuffix}`;
    }

    // 2. Meta Description: Target ~130-155 chars
    let generatedDesc = '';
    if (articleSubtitle && articleSubtitle.trim().length > 30) {
      generatedDesc = articleSubtitle.trim();
    } else if (articleContent && articleContent.trim().length > 0) {
      const stripped = articleContent
        .replace(/<[^>]*>/g, '')
        .replace(/[*#_`>~-]/g, '')
        .replace(/\[\^.*?\]/g, '')
        .replace(/\s+/g, ' ')
        .trim();
      generatedDesc = stripped.slice(0, 150);
      if (stripped.length > 150) generatedDesc += '...';
    } else {
      generatedDesc = `دراسة فكرية وبحث أكاديمي معمق بقلم ${articleAuthor} في مجال ${articleCategory}. استكشف الأبعاد والتحليلات النقدية.`;
    }

    // 3. Keywords: Extract main words from title & category
    const baseKeywords = [
      articleCategory,
      articleAuthor,
      'دراسات فكرية',
      'فلسفة',
      'مقالات نقدية'
    ];
    if (articleTitle) {
      const titleWords = articleTitle
        .split(/[\s,،؛-]+/)
        .filter(w => w.length > 3 && !['على', 'في', 'من', 'إلى', 'عن', 'مع', 'هذا', 'هذه', 'بين'].includes(w));
      baseKeywords.unshift(...titleWords.slice(0, 4));
    }
    const generatedKeywords = Array.from(new Set(baseKeywords)).join('، ');

    // 4. Canonical URL
    const slug = articleSlug || `article-${encodeURIComponent(articleTitle.slice(0, 30))}`;
    const generatedCanonical = `${window.location.origin}/?article=${slug}`;

    onChange({
      ...seo,
      metaTitle: generatedTitle,
      metaDescription: generatedDesc,
      focusKeywords: generatedKeywords,
      canonicalUrl: generatedCanonical,
      ogImage: articleCoverImage || seo.ogImage || '',
      authorName: articleAuthor,
      structuredDataType: 'Article',
      autoGenerated: true,
    });

    showToast('تم توليد بيانات السيو والكلمات المفتاحية للمقال بنجاح!');
  };

  // Structured Data JSON-LD
  const schemaJsonLd = {
    '@context': 'https://schema.org',
    '@type': 'ScholarlyArticle',
    'headline': metaTitle || articleTitle,
    'description': metaDescription || articleSubtitle || '',
    'author': {
      '@type': 'Person',
      'name': articleAuthor,
      'url': window.location.origin,
    },
    'datePublished': articlePublishedAt || new Date().toISOString(),
    'keywords': focusKeywords,
    'inLanguage': 'ar',
    'publisher': {
      '@type': 'Organization',
      'name': 'منصة الكاتب أيمن كناني للروايات والدراسات الفكرية',
      'url': window.location.origin,
    },
    'image': ogImage || undefined,
  };

  const handleCopySchema = () => {
    navigator.clipboard.writeText(JSON.stringify(schemaJsonLd, null, 2));
    setCopiedSchema(true);
    setTimeout(() => setCopiedSchema(false), 2000);
  };

  // Title & description lengths
  const titleLength = metaTitle.length;
  const descLength = metaDescription.length;

  return (
    <div className="space-y-6 text-right font-cairo" dir="rtl">
      {/* Notification Toast */}
      {toastMsg && (
        <div className="p-3 rounded-xl bg-emerald-50 border border-emerald-200 text-emerald-800 text-xs font-bold flex items-center gap-2 animate-in fade-in">
          <CheckCircle2 className="w-4 h-4 text-emerald-600 shrink-0" />
          <span>{toastMsg}</span>
        </div>
      )}

      {/* Header & Quick Action */}
      <div className="flex flex-wrap items-center justify-between gap-3 p-4 rounded-2xl bg-gradient-to-r from-[#4A5D4E]/10 via-[#FAF9F5] to-transparent border border-[#4A5D4E]/20">
        <div>
          <h4 className="text-sm font-bold text-[#2C2C2C] flex items-center gap-2">
            <Globe className="w-4 h-4 text-[#4A5D4E]" />
            <span>استوديو السيو المتقدم للمقال والدراسة (SEO Studio)</span>
          </h4>
          <p className="text-xs text-[#6E6A64] mt-0.5">
            ضبط ظهور المقال في محرك بحث جوجل وشبكات التواصل وبيانات Schema.org المنظمة
          </p>
        </div>

        <button
          type="button"
          onClick={handleAutoGenerate}
          className="px-3.5 py-1.5 rounded-xl bg-[#4A5D4E] hover:bg-[#38493C] text-white text-xs font-bold flex items-center gap-1.5 transition-all shadow-xs cursor-pointer"
        >
          <Sparkles className="w-3.5 h-3.5 text-amber-300" />
          <span>توليد السيو الذكي للمقال تلقائياً</span>
        </button>
      </div>

      {/* Inputs Form Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        {/* Meta Title */}
        <div className="space-y-1.5">
          <div className="flex items-center justify-between text-xs">
            <label className="font-bold text-[#2C2C2C]">
              عنوان السيو لمحركات البحث (Meta Title):
            </label>
            <span
              className={`font-mono text-[11px] font-bold ${
                titleLength >= 40 && titleLength <= 60
                  ? 'text-emerald-600'
                  : titleLength > 60
                  ? 'text-red-500'
                  : 'text-amber-600'
              }`}
            >
              {titleLength} / 60 حرفاً
            </span>
          </div>
          <input
            type="text"
            value={metaTitle}
            onChange={e => handleUpdate('metaTitle', e.target.value)}
            placeholder={articleTitle ? `${articleTitle} | دراسة فكرية` : 'عنوان السيو...'}
            className="w-full px-3.5 py-2 text-xs rounded-xl bg-white border border-[#E5E2D9] focus:border-[#4A5D4E] focus:ring-1 focus:ring-[#4A5D4E] text-[#2C2C2C] focus:outline-none"
          />
          <p className="text-[10px] text-[#8E8A83]">
            الطول المثالي بين 45 و 60 حرفاً، يشمل اسم الموضوع واسم الكاتب.
          </p>
        </div>

        {/* Focus Keywords */}
        <div className="space-y-1.5">
          <label className="block text-xs font-bold text-[#2C2C2C]">
            الكلمات المفتاحية المستهدفة (Focus Keywords):
          </label>
          <div className="relative">
            <input
              type="text"
              value={focusKeywords}
              onChange={e => handleUpdate('focusKeywords', e.target.value)}
              placeholder="فلسفة، نقد أدبي، دراسات، وعي..."
              className="w-full pr-8 pl-3 py-2 text-xs rounded-xl bg-white border border-[#E5E2D9] focus:border-[#4A5D4E] focus:ring-1 focus:ring-[#4A5D4E] text-[#2C2C2C] focus:outline-none"
            />
            <Tag className="w-3.5 h-3.5 text-[#8E8A83] absolute right-2.5 top-1/2 -translate-y-1/2" />
          </div>
          <p className="text-[10px] text-[#8E8A83]">
            افصل بين الكلمات المفتاحية بفاصلة عربية (،) أو إنجليزية (,).
          </p>
        </div>

        {/* Meta Description */}
        <div className="space-y-1.5 md:col-span-2">
          <div className="flex items-center justify-between text-xs">
            <label className="font-bold text-[#2C2C2C]">
              الوصف التعريفي للبحث (Meta Description):
            </label>
            <span
              className={`font-mono text-[11px] font-bold ${
                descLength >= 120 && descLength <= 160
                  ? 'text-emerald-600'
                  : descLength > 160
                  ? 'text-red-500'
                  : 'text-amber-600'
              }`}
            >
              {descLength} / 160 حرفاً
            </span>
          </div>
          <textarea
            rows={2}
            value={metaDescription}
            onChange={e => handleUpdate('metaDescription', e.target.value)}
            placeholder="مستخلص جذاب يوضح أطروحة المقال الفكرية والنتائج الرئيسية..."
            className="w-full px-3.5 py-2 text-xs rounded-xl bg-white border border-[#E5E2D9] focus:border-[#4A5D4E] focus:ring-1 focus:ring-[#4A5D4E] text-[#2C2C2C] focus:outline-none leading-relaxed resize-none"
          />
        </div>

        {/* Canonical URL */}
        <div className="space-y-1.5">
          <label className="block text-xs font-bold text-[#2C2C2C]">
            رابط المصدر الأكاديمي الدائم (Canonical URL):
          </label>
          <input
            type="url"
            value={canonicalUrl}
            onChange={e => handleUpdate('canonicalUrl', e.target.value)}
            placeholder="https://yourdomain.com/?article=slug"
            className="w-full px-3.5 py-2 text-xs rounded-xl bg-white border border-[#E5E2D9] focus:border-[#4A5D4E] focus:ring-1 focus:ring-[#4A5D4E] text-[#2C2C2C] focus:outline-none font-mono text-left"
            dir="ltr"
          />
        </div>

        {/* OG Share Image */}
        <div className="space-y-1.5">
          <label className="block text-xs font-bold text-[#2C2C2C]">
            صورة المعاينة في شبكات التواصل (OG Image URL):
          </label>
          <input
            type="url"
            value={ogImage}
            onChange={e => handleUpdate('ogImage', e.target.value)}
            placeholder="https://.../cover.jpg"
            className="w-full px-3.5 py-2 text-xs rounded-xl bg-white border border-[#E5E2D9] focus:border-[#4A5D4E] focus:ring-1 focus:ring-[#4A5D4E] text-[#2C2C2C] focus:outline-none font-mono text-left"
            dir="ltr"
          />
        </div>
      </div>

      {/* Indexing Policy Switch */}
      <div className="p-3.5 rounded-xl bg-[#FAF9F5] border border-[#E5E2D9] flex items-center justify-between">
        <div>
          <span className="text-xs font-bold text-[#2C2C2C] block">
            سياسة الفهرسة والأرشفة (Robots Indexing):
          </span>
          <span className="text-[11px] text-[#8E8A83]">
            {noIndex ? 'مستثنى من الفهرسة (noindex, nofollow)' : 'مفهرس ومتاح لجميع محركات البحث (index, follow)'}
          </span>
        </div>
        <button
          type="button"
          onClick={() => handleUpdate('noIndex', !noIndex)}
          className={`px-3 py-1.5 rounded-xl text-xs font-bold cursor-pointer transition-all ${
            noIndex
              ? 'bg-amber-100 text-amber-800 border border-amber-300'
              : 'bg-emerald-100 text-emerald-800 border border-emerald-300'
          }`}
        >
          {noIndex ? 'مخفي عن جوجل' : 'مفهرس تلقائياً'}
        </button>
      </div>

      {/* Live Google Search Snippet Preview */}
      <div className="p-4 rounded-2xl bg-white border border-[#E5E2D9] space-y-3">
        <div className="flex items-center justify-between border-b border-[#E5E2D9] pb-2">
          <span className="text-xs font-bold text-[#4A5D4E] flex items-center gap-1.5">
            <Search className="w-3.5 h-3.5" />
            <span>معاينة حية في نتائج بحث جوجل (Google Snippet Preview)</span>
          </span>

          {/* Mobile vs Desktop Toggle */}
          <div className="flex items-center bg-[#F5F2EA] p-0.5 rounded-lg text-xs">
            <button
              type="button"
              onClick={() => setPreviewDevice('mobile')}
              className={`px-2 py-1 rounded flex items-center gap-1 cursor-pointer ${
                previewDevice === 'mobile' ? 'bg-white text-[#4A5D4E] font-bold shadow-2xs' : 'text-[#6E6A64]'
              }`}
            >
              <Smartphone className="w-3 h-3" />
              <span>هاتف</span>
            </button>
            <button
              type="button"
              onClick={() => setPreviewDevice('desktop')}
              className={`px-2 py-1 rounded flex items-center gap-1 cursor-pointer ${
                previewDevice === 'desktop' ? 'bg-white text-[#4A5D4E] font-bold shadow-2xs' : 'text-[#6E6A64]'
              }`}
            >
              <Monitor className="w-3 h-3" />
              <span>كمبيوتر</span>
            </button>
          </div>
        </div>

        {/* Google Card Simulation */}
        <div
          className={`p-4 rounded-xl bg-[#FFFFFF] border border-[#E5E2D9] font-sans ${
            previewDevice === 'mobile' ? 'max-w-md mx-auto shadow-xs' : 'w-full'
          }`}
          dir="rtl"
        >
          {/* URL row */}
          <div className="flex items-center gap-2 mb-1">
            <div className="w-4 h-4 rounded-full bg-[#4A5D4E] text-white text-[9px] font-bold flex items-center justify-center">
              أ
            </div>
            <div className="flex flex-col text-[11px] leading-tight overflow-hidden">
              <span className="text-[#202124] font-medium truncate">منصة الكاتب أيمن كناني</span>
              <span className="text-[#5f6368] text-[10px] truncate" dir="ltr">
                {canonicalUrl || 'https://aymankinani.com/articles/' + (articleSlug || 'study-1')}
              </span>
            </div>
          </div>

          {/* Title */}
          <h4 className="text-base sm:text-lg font-medium text-[#1a0dab] hover:underline cursor-pointer leading-snug line-clamp-2">
            {metaTitle || articleTitle || 'عنوان الدراسة الفكرية في منصة الكاتب أيمن كناني'}
          </h4>

          {/* Description Snippet */}
          <p className="text-xs text-[#4d5156] leading-relaxed mt-1 line-clamp-2">
            <span className="text-[#70757a] text-[11px] ml-1">
              {new Date().toLocaleDateString('ar-EG')} —
            </span>
            {metaDescription || articleSubtitle || 'استكشف أحدث المقالات والدراسات الفكرية والنقدية للكاتب أيمن كناني بأعلى معايير التوثيق الأكاديمي والتحليل.'}
          </p>
        </div>
      </div>

      {/* Schema.org Structured Data Preview & Copy */}
      <div className="p-4 rounded-2xl bg-[#FAF9F5] border border-[#E5E2D9] space-y-2">
        <div className="flex items-center justify-between">
          <span className="text-xs font-bold text-[#2C2C2C] flex items-center gap-1.5">
            <Code className="w-3.5 h-3.5 text-[#C88A3B]" />
            <span>كود Schema.org للبيانات المنظمة (ScholarlyArticle JSON-LD)</span>
          </span>
          <button
            type="button"
            onClick={handleCopySchema}
            className="px-2.5 py-1 text-[11px] font-bold rounded-lg border border-[#E5E2D9] bg-white hover:bg-[#F0ECE1] text-[#4A5D4E] flex items-center gap-1 cursor-pointer"
          >
            {copiedSchema ? <Check className="w-3 h-3 text-emerald-600" /> : <Copy className="w-3 h-3" />}
            <span>{copiedSchema ? 'تم النسخ!' : 'نسخ كود Schema'}</span>
          </button>
        </div>
        <pre
          className="p-3 rounded-xl bg-[#2C2C2C] text-[#E4E4E7] text-[10px] font-mono overflow-x-auto max-h-36 no-scrollbar text-left"
          dir="ltr"
        >
          {JSON.stringify(schemaJsonLd, null, 2)}
        </pre>
      </div>
    </div>
  );
};
