export type NovelStatus = 'ONGOING' | 'COMPLETED' | 'HIATUS';
export type ChapterStatus = 'PUBLISHED' | 'DRAFT' | 'SCHEDULED';
export type Genre = string;

export interface Category {
  id: string;
  name: string;
  arabicName: string;
  description?: string;
  icon?: string;
}

export interface AuthorSocialLinks {
  twitter?: string;
  facebook?: string;
  instagram?: string;
  youtube?: string;
  telegram?: string;
  linkedin?: string;
  tiktok?: string;
  goodreads?: string;
  whatsapp?: string;
  email?: string;
  website?: string;
}

export interface AuthorProfile {
  name: string;
  englishName: string;
  title: string;
  avatar: string;
  coverImage?: string;
  shortBio: string;
  fullBio: string;
  location: string;
  vision?: string;
  socialLinks: AuthorSocialLinks;
  contactEmail: string;
}

export interface SiteBranding {
  siteName: string;
  siteSubtitle: string;
  logoUrl: string;
  faviconUrl: string;
  pwaIconUrl?: string;
  footerText: string;
}

export interface SeoSettings {
  siteTitleTemplate: string;
  defaultTitle: string;
  defaultDescription: string;
  keywords: string;
  canonicalBaseUrl: string;
  authorName: string;
  twitterHandle: string;
  googleVerificationCode: string;
  bingVerificationCode: string;
  ogDefaultImage: string;
  enableStructuredData: boolean;
  indexingPolicy: 'all' | 'noindex';
}

export interface DonationSettings {
  enabled: boolean;
  title: string;
  description: string;
  paypalEmailOrLink: string;
  buyMeACoffeeUrl: string;
  patreonUrl: string;
  kofiUrl: string;
  bankAccountDetails: string;
  cryptoWallet: string;
  customPaymentLink: string;
  customPaymentTitle: string;
}

export interface SupabaseConfig {
  enabled: boolean;
  url: string;
  anonKey: string;
  lastSyncTime?: string;
  autoSync: boolean;
  connected?: boolean;
}

export interface LegalDocuments {
  termsOfService: string;
  privacyPolicy: string;
  dmcaPolicy: string;
  licensesPolicy?: string;
  publisherInfo: string;
  contactEmail: string;
  supportEmail: string;
  lastUpdated: string;
}

export interface ContactMessage {
  id: string;
  name: string;
  email: string;
  subject?: string;
  message: string;
  createdAt: string;
  read: boolean;
}

export interface TableOfContentItem {
  id: string;
  title: string;
  anchor?: string;
  level?: number;
  url?: string;
  chapterNumber?: number;
  slug?: string;
  chapterId?: string;
}

export interface NovelSeoMeta {
  metaTitle?: string;
  metaDescription?: string;
  focusKeywords?: string;
  canonicalUrl?: string;
  ogImage?: string;
  authorName?: string;
  noIndex?: boolean;
  structuredDataType?: 'Book' | 'CreativeWork' | 'Article';
  deweyDecimal?: string;
  deweyCategoryName?: string;
  autoGenerated?: boolean;
  tableOfContents?: TableOfContentItem[];
}

export interface ChapterSeoMeta {
  metaTitle?: string;
  metaDescription?: string;
  focusKeywords?: string;
  canonicalUrl?: string;
  ogImage?: string;
  noIndex?: boolean;
  autoGenerated?: boolean;
}

export interface Novel {
  id: string;
  title: string;
  slug: string;
  author: string;
  authorBio: string;
  synopsis: string;
  coverImage: string;
  bannerImage: string;
  genres: Genre[];
  tags: string[];
  status: NovelStatus;
  totalViews: number;
  totalLikes: number;
  rating: number; // 1-5
  ratingCount: number;
  createdAt: string;
  updatedAt: string;
  isFeatured?: boolean;
  pdfDownloadUrl?: string; // Direct PDF link or Drive/Cloud download URL
  pdfFileSize?: string; // e.g. "12.4 MB"
  downloadButtonText?: string; // e.g. "تحميل الكتاب PDF" or custom text
  deweyDecimal?: string; // Dewey Decimal Classification code (e.g. "813", "810.9")
  deweyCategoryName?: string; // Description (e.g. "813 - الروايات والقصص العربية")
  tableOfContents?: TableOfContentItem[];
  seo?: NovelSeoMeta;
}

export interface Chapter {
  id: string;
  novelId: string;
  chapterNumber: number;
  title: string;
  slug: string;
  content: string;
  authorNote?: string;
  publishedAt: string;
  views: number;
  likes: number;
  wordCount: number;
  status: ChapterStatus;
  seo?: ChapterSeoMeta;
}

export interface Comment {
  id: string;
  chapterId: string;
  novelId: string;
  authorName: string;
  authorAvatar?: string;
  content: string;
  createdAt: string;
  likes: number;
  userLiked?: boolean;
  isAuthor?: boolean;
  isPinned?: boolean;
  parentId?: string; // for nested replies
}

export type ReaderFontFamily = 'amiri' | 'cairo' | 'tajawal' | 'scheherazade' | 'readex' | 'lora' | 'jakarta';
export type ReaderTheme = 'paper' | 'sepia' | 'slate' | 'obsidian' | 'emerald';
export type ReaderWidth = 'narrow' | 'standard' | 'wide' | 'full';
export type ReaderLineHeight = 'tight' | 'normal' | 'relaxed';

export interface ReaderSettings {
  fontFamily: ReaderFontFamily;
  fontSize: number; // 14 to 32
  lineHeight: ReaderLineHeight;
  theme: ReaderTheme;
  contentWidth: ReaderWidth;
  textAlign: 'right' | 'justify' | 'left';
  paragraphSpacing: 'normal' | 'spacious';
  bionicReading: boolean;
  autoScrollSpeed?: number; // 0 = off, 1-5 = slow to fast
}

export type AdType = 'adsense' | 'adsterra' | 'corporate' | 'custom_banner';

export interface AdPlacement {
  id: string;
  name: string;
  location: 'header' | 'sidebar' | 'mid_chapter' | 'chapter_end' | 'footer' | 'floating_bottom';
  enabled: boolean;
  type: AdType;
  adSlotId?: string; // AdSense slot ID
  adFormat?: 'auto' | 'rectangle' | 'horizontal' | 'vertical';
  corporateSponsorId?: string;
  customHtml?: string;
  adsterraKey?: string;
  adsterraScript?: string;
  adsterraBannerSize?: '728x90' | '300x250' | '160x600' | '320x50' | '468x60' | 'native';
}

export interface CorporateSponsor {
  id: string;
  sponsorName: string;
  tagline: string;
  badge: string;
  imageUrl: string;
  targetUrl: string;
  ctaText: string;
  active: boolean;
  impressions: number;
  clicks: number;
}

export interface GoogleAdSenseConfig {
  enabled: boolean;
  publisherId: string; // e.g. ca-pub-1234567890123456
  autoAds: boolean;
  testMode: boolean;
  adsTxtContent: string;
}

export interface AdsterraConfig {
  enabled: boolean;
  popunderScript?: string;
  socialBarScript?: string;
  directLinkUrl?: string;
  nativeBannerScript?: string;
}

export interface AdSettings {
  googleAdSense: GoogleAdSenseConfig;
  adsterra?: AdsterraConfig;
  placements: Record<string, AdPlacement>;
  corporateSponsors: CorporateSponsor[];
}

export interface Bookmark {
  novelId: string;
  chapterId: string;
  chapterNumber: number;
  chapterTitle: string;
  updatedAt: string;
}

export interface ReadingHistoryItem {
  novelId: string;
  chapterId: string;
  chapterNumber: number;
  chapterTitle: string;
  readAt: string;
  progressPercent: number;
}

export type IntellectualType = 'article' | 'study' | 'translated_article' | 'book';

export interface MultilingualAbstract {
  ar?: string; // العربية
  en?: string; // English
  fr?: string; // Français
}

export interface MarginNote {
  id: string;
  targetType: 'article' | 'chapter';
  targetId: string; // articleId or chapterId
  novelId?: string; // for chapters
  selectedText: string;
  paragraphIndex?: number;
  note: string;
  authorName: string;
  createdAt: string;
  likes?: number;
  userLiked?: boolean;
  noteType?: 'comment' | 'question' | 'critique' | 'glossary';
}

export type ArticleReaderNote = MarginNote;

export interface ParallelSegment {
  id: string;
  originalText: string;
  translatedText: string;
  sectionTitle?: string;
  notes?: string;
}

export interface IntellectualItem {
  id: string;
  title: string;
  subtitle?: string;
  originalTitle?: string; // e.g. "What Is It Like to Be a Bat?"
  slug: string;
  type: 'article' | 'study' | 'translated_article';
  author: string;
  originalAuthor?: string; // e.g. "توماس ناغل (Thomas Nagel)"
  translator?: string; // e.g. "أيمن كناني"
  originalLanguage?: string; // e.g. "الإنجليزية"
  originalSource?: string; // e.g. "The Philosophical Review, Vol. 83"
  originalYear?: string; // e.g. "1974"
  abstract?: string; // مستخلص البحث أو ملخص المقال
  multilingualAbstract?: MultilingualAbstract; // ملخص متعدد اللغات (عربي، إنجليزي، فرنسي)
  content: string; // النص الكامل المنسق (باللغة العربية)
  originalContent?: string; // النص الكامل باللغة الأصلية (للترجمات والدراسات المقارنة)
  parallelSegments?: ParallelSegment[]; // فقرات متوازية للمزامنة السطرية
  category: string; // فلسفة، علم نفس، نقد أدبي، ذكاء اصطناعي، أدب، اجتماع
  tags: string[];
  readingTimeMinutes: number;
  wordCount: number;
  views: number;
  likes: number;
  publishedAt: string;
  references?: string[]; // مراجع ومصادر البحث الأكاديمي
  footnotes?: { id: number; text: string }[]; // هوامش وإحالات
  commentaryStudies?: Array<{ id: string; title: string; author: string; studyType?: string; content?: string; articleId?: string }>; // دراسات تعقيبية مرتبطة
  isFeatured?: boolean;
  isReaderContribution?: boolean;
  status?: 'PUBLISHED' | 'DRAFT';
  coverImage?: string;
  deweyDecimal?: string;
  doi?: string; // Digital Object Identifier
  pdfDownloadUrl?: string;
}

export interface UnifiedSearchResult {
  id: string;
  type: 'book' | 'chapter' | 'study' | 'article' | 'translated_article';
  title: string;
  subtitle?: string;
  author: string;
  originalAuthor?: string;
  translator?: string;
  category: string;
  snippet: string;
  date: string;
  coverImage?: string;
  views?: number;
  likes?: number;
  // If chapter:
  novelId?: string;
  novelTitle?: string;
  chapterNumber?: number;
  chapterId?: string;
  // If book:
  chapters?: Array<{ id: string; chapterNumber: number; title: string; views?: number }>;
  chaptersCount?: number;
  deweyCode?: string;
  tags?: string[];
  pdfDownloadUrl?: string;
  // If article/study/translated:
  readingTimeMinutes?: number;
  referencesCount?: number;
  slug?: string;
}
